// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const { login } = require('../login');
describe('DMK-07', function() {
  this.timeout(80000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('MicrosoftEdge').build()
    await driver.manage().window().maximize();
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('DMK-07', async function() {
    await login(driver, "minhanh1998", "NewPwd@1");
    await driver.get("https://meowshopp.com/")
    await driver.findElement(By.css(".e-fas-user > path")).click()
    await driver.sleep(2000)
    const doiMatKhauBtn = await driver.findElement(
      By.linkText("Đổi mật khẩu")
    );

    // scroll tới element
    await driver.executeScript(
        "arguments[0].scrollIntoView({block:'center'});",
        doiMatKhauBtn
    );

    await driver.sleep(1000);

    // click bằng javascript
    await driver.executeScript(
        "arguments[0].click();",
        doiMatKhauBtn
    );
    await driver.sleep(2000)
    await driver.executeScript("window.scrollBy(0, 300);")
    await driver.findElement(By.name("old_password")).sendKeys()
    await driver.findElement(By.name("new_password")).sendKeys()
    await driver.findElement(By.name("confirm_password")).sendKeys()
    await driver.findElement(By.name("change_password_submit")).click()
    await driver.sleep(2000)
    {
      const elements = await driver.findElements(By.css("input:invalid"))
      assert(elements.length)
    }
  })
})
