// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const { login } = require('../login');
describe('TT-02', function() {
  this.timeout(80000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('MicrosoftEdge').build()
    await driver.manage().window().maximize();
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
   async function scrollTo(driver, element) {
      await driver.executeScript(
          "arguments[0].scrollIntoView({block:'center'});",
          element
      );
    }
    it('TT-02', async function() {
      await login(driver);
      await driver.get("https://meowshopp.com/?add-to-cart=604");
      await driver.get("https://meowshopp.com/")
      await driver.findElement(By.linkText("THANH TOÁN")).click()
      await driver.sleep(5000)
      assert(await driver.getTitle() == "THANH TOÁN -")
      const firstName = await driver.findElement(By.id("billing_first_name"));
      await scrollTo(driver, firstName);
      await firstName.sendKeys("Thu Hà");
  
      const lastName = await driver.findElement(By.id("billing_last_name"));
      await scrollTo(driver, lastName);
      await lastName.sendKeys("Phạm");
  
      const phone = await driver.findElement(By.id("billing_phone"));
      await scrollTo(driver, phone);
      await phone.sendKeys("0934567890");
  
      const state = await driver.findElement(By.id("select2-billing_state-container"));
      await scrollTo(driver, state);
      await state.click();
      await driver.sleep(500);
      const stateOption = await driver.findElement(
          By.xpath("//li[contains(.,'Thành phố Hải Phòng')]")
      );
      await scrollTo(driver, stateOption);
      await stateOption.click();
      await driver.sleep(5000);
  
      const city = await driver.findElement(By.id("select2-billing_city-container"));
      await scrollTo(driver, city);
      await city.click();
      await driver.sleep(500);
      const cityOption = await driver.findElement(
          By.xpath("//li[contains(.,'Phường Lê Chân')]")
      );
      await scrollTo(driver, cityOption);
      await cityOption.click();
      await driver.sleep(2000);
  
      const address = await driver.findElement(By.id("billing_address_1"));
      await scrollTo(driver, address);
      await address.sendKeys("45 Tô Hiệu, Quận Lê Chân");
      await driver.sleep(500);
  
      const note = await driver.findElement(By.id("order_comments"));
      await scrollTo(driver, note);
      await note.sendKeys();
      await driver.sleep(500);
  
      const paymentMethod = await driver.findElement(By.id("payment_method_bacs"));
      await scrollTo(driver, paymentMethod);
      await paymentMethod.click();
      await driver.sleep(2000);
  
      const placeOrder = await driver.findElement(By.id("place_order"));
      await driver.executeScript(
        "arguments[0].scrollIntoView({block: 'center'});",
        placeOrder
      );
      await driver.executeScript("arguments[0].click();", placeOrder);
  
      await driver.sleep(8000)
      {
        const elements = await driver.findElements(By.css(".woocommerce-order"))
        assert(elements.length)
      }
      await driver.sleep(1000);
  })
})
