// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const fs = require('fs')
const path = require('path')
describe('LH-05', function() {
  this.timeout(80000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('MicrosoftEdge').build()
    await driver.manage().window().maximize();
    vars = {}
  // mở website trước
    await driver.get("https://meowshopp.com/")

    console.log("Đã mở website")

    try {

      // đường dẫn cookie
      const cookiePath = path.join(
        __dirname,
        '../cookies.json'
      )

      console.log("Đường dẫn cookie:", cookiePath)

      // đọc cookie
      let cookies = JSON.parse(
        fs.readFileSync(cookiePath)
      )

      console.log("Đọc cookie thành công")

      // add cookie
      for (let cookie of cookies) {

        // tránh lỗi expiry
        if (cookie.expiry) {
          delete cookie.expiry
        }

        await driver.manage().addCookie(cookie)
      }

      console.log("Add cookie thành công")

      // refresh để login
      await driver.navigate().refresh()

      console.log("Refresh thành công")

      await driver.sleep(5000)

    } catch (error) {

      console.log("Lỗi cookie:")
      console.log(error)

    }

  })
  afterEach(async function() {
    await driver.quit();
  })
  it('LH-05', async function() {
    await driver.get("https://meowshopp.com/")
    await driver.findElement(By.linkText("LIÊN HỆ")).click()
    await driver.sleep(2000)
    await driver.findElement(By.id("wpforms-1617-field_4")).sendKeys()
    await driver.findElement(By.id("wpforms-1617-field_1")).sendKeys()
    await driver.findElement(By.id("wpforms-1617-field_2")).sendKeys()
    const submitBtn = await driver.findElement(
        By.id("wpforms-submit-1617")
    );
    await driver.executeScript(
      "arguments[0].scrollIntoView({block:'center'});",
      submitBtn
    );
      await driver.sleep(1000);

    await driver.executeScript(
      "arguments[0].click();",
      submitBtn
    );
    await driver.sleep(2000)
    {
      const elements = await driver.findElements(By.id("wpforms-1617-field_4-error"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.id("wpforms-1617-field_1-error"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.id("wpforms-1617-field_2-error"))
      assert(elements.length)
    }
  })
})
