// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TD_DN_02', function() {
  this.timeout(80000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('MicrosoftEdge').build()
    await driver.manage().window().maximize();
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TD_DN_02', async function() {
    await driver.get("https://meowshopp.com/")
    await driver.findElement(By.css(".e-fas-user > path")).click()
    await driver.sleep(3000)
    await driver.findElement(By.id("username-581")).sendKeys("minhanh1998")
    await driver.findElement(By.id("user_password-581")).sendKeys("MinhAnh@98")
    await driver.findElement(By.id("um-submit-btn")).click()
    await driver.sleep(5000)
    assert(await driver.getTitle() == "TRANG CHỦ")
  })
})
