// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const { login } = require('../login');
describe('GG-07', function() {
  this.timeout(80000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('MicrosoftEdge').build()
    await driver.manage().window().maximize();
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function scrollTo(driver, element) {
    await driver.executeScript(
        "arguments[0].scrollIntoView({block:'center'});",
        element
    );
  }
  it('GG-07', async function() {
    await login(driver);
    await driver.get("https://meowshopp.com/?add-to-cart=604");
    await driver.get("https://meowshopp.com/")
    await driver.findElement(By.linkText("THANH TOÁN")).click()
    await driver.sleep(2000)
    const firstName = await driver.findElement(By.id("billing_first_name"));
    await scrollTo(driver, firstName);
    await firstName.sendKeys("Quốc Bảo");
    const lastName = await driver.findElement(By.id("billing_last_name"));
    await scrollTo(driver, lastName);
    await lastName.sendKeys("Hoàng");
    const phone = await driver.findElement(By.id("billing_phone"));
    await scrollTo(driver, phone);
    await phone.sendKeys("0768901234");
    const state = await driver.findElement(By.id("select2-billing_state-container"));
    await scrollTo(driver, state);
    await state.click();
    const stateOption = await driver.findElement(By.xpath("//li[contains(.,'Thành phố Cần Thơ')]"));
    await scrollTo(driver, stateOption);
    await stateOption.click();
    await driver.sleep(2000);
    const city = await driver.findElement(By.id("select2-billing_city-container"));
    await scrollTo(driver, city);
    await city.click();
    const cityOption = await driver.findElement(By.xpath("//li[contains(.,'Phường Tân An')]"));
    await scrollTo(driver, cityOption);
    await cityOption.click();
    await driver.sleep(2000);
    const address = await driver.findElement(By.id("billing_address_1"));
    await scrollTo(driver, address);
    await address.sendKeys("102 đường 30 Tháng 4, Quận Ninh Kiều");
    const note = await driver.findElement(By.id("order_comments"));
    await scrollTo(driver, note);
    await note.sendKeys("Giao hàng giờ hành chính, gọi trước khi đến");
    const couponTrigger = await driver.findElement(By.id("ast-coupon-trigger"));
    await scrollTo(driver, couponTrigger);
    await couponTrigger.click();
    const couponCode = await driver.findElement(By.id("ast-coupon-code"));
    await scrollTo(driver, couponCode);
    await couponCode.sendKeys();
    const applyCoupon = await driver.findElement(By.id("ast-apply-coupon"));
    await scrollTo(driver, applyCoupon);
    await applyCoupon.click();
    await driver.sleep(3000);
    {
      const elements = await driver.findElements(By.id("coupon-error-notice"))
      assert(elements.length)
    }

    const paymentMethod = await driver.findElement(By.id("payment_method_cod"));
    await scrollTo(driver, paymentMethod);
    await paymentMethod.click();
    await driver.sleep(3000);

    const placeOrder = await driver.findElement(By.id("place_order"));
    await driver.executeScript(
      "arguments[0].scrollIntoView({block: 'center'});",
      placeOrder
    );
    await driver.executeScript("arguments[0].click();", placeOrder);

    await driver.sleep(10000)
    {
      const elements = await driver.findElements(By.css(".woocommerce-order"))
      assert(elements.length)
    }
    await driver.sleep(1000);
  })
})
