// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('QD_DK_08', function() {
  this.timeout(60000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('MicrosoftEdge').build()
    await driver.manage().window().maximize();
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('QD_DK_08', async function() {
    await driver.get("https://meowshopp.com/")
    await driver.findElement(By.css(".e-fas-user > path")).click()
    await driver.sleep(3000)
    await driver.findElement(By.linkText("Đăng ký")).click()
    await driver.sleep(3000)
    await driver.findElement(By.id("user_login-580")).sendKeys("thuhien_ng")
    await driver.findElement(By.id("first_name-580")).sendKeys("Trương")
    await driver.findElement(By.id("last_name-580")).sendKeys("H")
    await driver.findElement(By.id("user_email-580")).sendKeys()
    await driver.findElement(By.id("user_password-580")).sendKeys()
    await driver.findElement(By.id("confirm_user_password-580")).sendKeys()
    const submitBtn = await driver.findElement(By.id("um-submit-btn"));

    await driver.executeScript(
      "arguments[0].scrollIntoView({block:'center'});",
      submitBtn
    );

    await driver.sleep(1000);

    await driver.executeScript(
      "arguments[0].click();",
      submitBtn
    );
    await driver.sleep(5000)
    {
      const elements = await driver.findElements(By.id("um-error-for-last_name-580"))
      assert(elements.length)
    }
  })
})
