// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('QD_DK_01', function() {
  this.timeout(60000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('MicrosoftEdge').build()
    await driver.manage().window().maximize();
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('QD_DK_01', async function() {
    await driver.get("https://meowshopp.com/")
    await driver.findElement(By.css(".e-fas-user")).click()
    await driver.sleep(3000)
    await driver.findElement(By.linkText("Đăng ký")).click()
    await driver.sleep(3000)
    await driver.findElement(By.id("user_login-580")).sendKeys("nguyenvana123")
    await driver.findElement(By.id("first_name-580")).sendKeys("Nguyen")
    await driver.findElement(By.id("last_name-580")).sendKeys("Van A")
    await driver.findElement(By.id("user_email-580")).sendKeys("nguyenvana123@gmail.com")
    await driver.findElement(By.id("user_password-580")).sendKeys("Password@123")
    await driver.findElement(By.id("confirm_user_password-580")).sendKeys("Password@123")
    const submitBtn = await driver.findElement(By.id("um-submit-btn"));

    await driver.executeScript(
      "arguments[0].scrollIntoView({block:'center'});",
      submitBtn
    );

    await driver.sleep(1000);

    await driver.executeScript(
      "arguments[0].click();",
      submitBtn
    );
    await driver.sleep(6000)
    assert(await driver.getTitle() == "Account Page -")
  })
})
