name: Selenium Automation Test

on:
  push:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Register Tests
        run: npm run test-dk

      - name: Run Login Tests
        run: npm run test-dn

      - name: Run Change Password Tests
        run: npm run test-dmk

      - name: Run Discount Tests
        run: npm run test-gg

      - name: Run Billing Information Tests
        run: npm run test-ttin-ttoan
