// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('QD_DN_06', function() {
  this.timeout(80000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('MicrosoftEdge').build()
    await driver.manage().window().maximize();
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('QD_DN_06', async function() {
    await driver.get("https://meowshopp.com/")
    await driver.findElement(By.css(".e-fas-user > path")).click()
    await driver.sleep(3000)
    await driver.findElement(By.id("username-581")).sendKeys()
    await driver.findElement(By.id("user_password-581")).sendKeys()
    await driver.findElement(By.id("um-submit-btn")).click()
    await driver.sleep(5000)
    {
      const elements = await driver.findElements(By.id("um-error-for-username-581"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.id("um-error-for-user_password-581"))
      assert(elements.length)
    }
  })
})
